// views/Login.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { AuthState } from '../types';
import { ABSService } from '../services/absService';
import { Link as LinkIcon, User, Lock, Activity, Headphones, AlertCircle } from 'lucide-vue-next';

const emit = defineEmits<{
  (e: 'login', auth: AuthState): void
}>();

const serverUrl = ref('https://api.robertsaedal.xyz');
const username = ref('');
const password = ref('');
const processing = ref(false);
const error = ref<string | null>(null);

onMounted(async () => {
  const savedAuth = localStorage.getItem('rs_auth');
  if (savedAuth) {
    try {
      const auth = JSON.parse(savedAuth) as AuthState;
      if (auth.user?.token) {
        processing.value = true;
        const authorizeRes = await ABSService.authorize(auth.serverUrl, auth.user.token);
        if (authorizeRes) {
          emit('login', auth);
        }
      }
    } catch (e: any) {
      console.error('Auto-login check failed', e);
      localStorage.removeItem('rs_auth');
      error.value = e.message || 'Stored session invalid.';
    } finally {
      processing.value = false;
    }
  }
});

const submitForm = async () => {
  error.value = null;
  processing.value = true;

  try {
    const normalizedUrl = ABSService.normalizeUrl(serverUrl.value);
    const authRes = await ABSService.login(normalizedUrl, username.value, password.value);
    const token = authRes.user.accessToken || authRes.user.token;
    
    if (!token) {
      throw new Error('No access token received from portal.');
    }

    const authorizeRes = await ABSService.authorize(normalizedUrl, token);
    
    if (authorizeRes) {
      const authData: AuthState = {
        serverUrl: normalizedUrl,
        user: { 
          id: authorizeRes.user.id, 
          username: authorizeRes.user.username, 
          token: token
        }
      };

      localStorage.setItem('rs_auth', JSON.stringify(authData));
      emit('login', authData);
    }
  } catch (err: any) {
    console.error('Portal connection failed', err);
    error.value = err.message || 'Connection failed: Check URL and Credentials';
  } finally {
    processing.value = false;
  }
};
</script>

<template>
  <div class="flex-1 flex flex-col items-center justify-center p-8 bg-black h-[100dvh] overflow-hidden relative">
    <div class="absolute inset-0 z-0 overflow-hidden pointer-events-none">
      <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-purple-600/10 rounded-full blur-[120px] animate-pulse" />
      <div class="absolute top-0 right-0 w-[300px] h-[300px] bg-purple-900/10 rounded-full blur-[80px]" />
    </div>

    <div class="w-full max-w-md space-y-10 animate-fade-in relative z-10">
      <div class="text-center flex flex-col items-center">
        <div class="w-24 h-24 rounded-[32px] overflow-hidden shadow-[0_0_50px_rgba(157,80,187,0.3)] mb-8 bg-neutral-900 border border-purple-500/20 flex items-center justify-center group relative">
          <Headphones :size="40" class="text-purple-500 drop-shadow-[0_0_10px_rgba(157,80,187,0.8)] transition-transform group-hover:scale-110 duration-700" />
        </div>
        <h1 class="text-3xl font-black tracking-tighter text-white mb-2 leading-tight">
          ARCHIVE <span class="text-purple-500 drop-shadow-aether-glow">PORTAL</span>
        </h1>
        <div class="flex items-center justify-center gap-3">
          <Activity :size="10" class="text-purple-600 animate-pulse" />
          <p class="text-neutral-600 uppercase tracking-[0.6em] text-[9px] font-black">Secure Endpoint Authorized</p>
        </div>
      </div>

      <div class="bg-neutral-900/40 backdrop-blur-2xl border border-purple-500/30 rounded-[40px] p-8 shadow-2xl relative overflow-hidden group">
        <div class="absolute inset-0 bg-gradient-to-br from-purple-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />
        
        <div v-if="error" class="flex items-center gap-3 text-red-400 text-center py-4 px-4 mb-6 bg-red-500/10 border border-red-500/20 rounded-2xl text-[10px] font-black uppercase tracking-widest animate-shake">
          <AlertCircle :size="14" class="shrink-0" />
          <span>{{ error }}</span>
        </div>

        <form @submit.prevent="submitForm" class="space-y-5">
          <div class="space-y-1.5">
            <label class="text-[9px] font-black text-neutral-500 uppercase tracking-[0.2em] ml-5">Portal Address</label>
            <div class="relative group">
              <LinkIcon :size="14" class="absolute left-6 top-1/2 -translate-y-1/2 text-neutral-600 group-focus-within:text-purple-500 transition-colors" />
              <input
                type="text"
                v-model="serverUrl"
                :disabled="processing"
                placeholder="https://your-server.xyz"
                class="w-full bg-neutral-900/80 border border-white/10 py-5 pl-14 pr-8 rounded-[24px] text-white placeholder-neutral-700 font-bold text-xs tracking-tight outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/20 transition-all disabled:opacity-50"
                required
              />
            </div>
          </div>

          <div class="space-y-1.5">
            <label class="text-[9px] font-black text-neutral-500 uppercase tracking-[0.2em] ml-5">Identifier</label>
            <div class="relative group">
              <User :size="14" class="absolute left-6 top-1/2 -translate-y-1/2 text-neutral-600 group-focus-within:text-purple-500 transition-colors" />
              <input
                type="text"
                v-model="username"
                :disabled="processing"
                placeholder="Username"
                class="w-full bg-neutral-900/80 border border-white/10 py-5 pl-14 pr-8 rounded-[24px] text-white placeholder-neutral-700 font-bold text-xs tracking-tight outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/20 transition-all disabled:opacity-50"
                required
              />
            </div>
          </div>

          <div class="space-y-1.5">
            <label class="text-[9px] font-black text-neutral-500 uppercase tracking-[0.2em] ml-5">Passkey</label>
            <div class="relative group">
              <Lock :size="14" class="absolute left-6 top-1/2 -translate-y-1/2 text-neutral-600 group-focus-within:text-purple-500 transition-colors" />
              <input
                type="password"
                v-model="password"
                :disabled="processing"
                placeholder="Password"
                class="w-full bg-neutral-900/80 border border-white/10 py-5 pl-14 pr-8 rounded-[24px] text-white placeholder-neutral-700 font-bold text-xs tracking-tight outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/20 transition-all disabled:opacity-50"
              />
            </div>
          </div>

          <button
            type="submit"
            :disabled="processing"
            class="w-full gradient-aether py-6 rounded-[28px] font-black text-sm uppercase tracking-[0.3em] shadow-[0_10px_30px_rgba(157,80,187,0.4)] active:scale-[0.98] transition-all text-white mt-8 disabled:opacity-50 disabled:grayscale disabled:scale-100 flex items-center justify-center gap-3 overflow-hidden"
          >
            <span v-if="processing" class="flex items-center gap-2">
              <div class="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
              CHECKING...
            </span>
            <span v-else>INITIALIZE LINK</span>
          </button>
        </form>
      </div>

      <div class="text-center pt-6 opacity-30">
        <p class="text-[8px] font-black text-neutral-400 uppercase tracking-[0.5em]">Premium Minimalism • Archive Client v5.2</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.animate-shake {
  animation: shake 0.5s cubic-bezier(.36,.07,.19,.97) both;
}
@keyframes shake {
  10%, 90% { transform: translate3d(-1px, 0, 0); }
  20%, 80% { transform: translate3d(2px, 0, 0); }
  30%, 50%, 70% { transform: translate3d(-4px, 0, 0); }
  40%, 60% { transform: translate3d(4px, 0, 0); }
}
.animate-fade-in {
  animation: fade-in 0.8s cubic-bezier(0.2, 0.8, 0.2, 1) forwards;
}
@keyframes fade-in {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>

// components/Login.tsx
import React, { useState } from 'react';
import { AuthState } from '../types';
import { ABSService } from '../services/absService';
import { ShieldAlert, Link as LinkIcon, User, Lock, Activity, Headphones } from 'lucide-react';

interface LoginProps {
  onLogin: (auth: AuthState) => void;
}

const Login: React.FC<LoginProps> = ({ onLogin }) => {
  const [serverUrl, setServerUrl] = useState('https://api.robertsaedal.xyz');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<React.ReactNode>('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const data = await ABSService.login(serverUrl, username, password);
      
      let finalUrl = serverUrl.trim().replace(/\/+$/, '').replace(/\/api$/, '');
      if (!finalUrl.startsWith('http')) {
        finalUrl = `${window.location.protocol === 'https:' ? 'https://' : 'http://'}${finalUrl}`;
      }

      onLogin({
        serverUrl: finalUrl,
        user: { 
          id: data.user.id, 
          username: data.user.username, 
          token: data.user.token 
        }
      });
    } catch (err: any) {
      if (err.message === 'CORS_ERROR') {
        setError(
          <div className="space-y-2">
            <p className="text-red-400 font-black uppercase text-[10px] tracking-widest">Connection Blocked (CORS)</p>
            <p className="text-neutral-500 text-[9px] leading-relaxed uppercase font-bold text-center">
              Add this origin to Audiobookshelf Allowed Origins:
              <br />
              <span className="text-purple-500 break-all mt-1 block font-mono">{window.location.origin}</span>
            </p>
          </div>
        );
      } else {
        setError(err.message || 'Access Denied: Check Credentials');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex-1 flex flex-col items-center justify-center p-8 bg-black h-[100dvh] overflow-hidden">
      <div className="w-full max-w-md space-y-12 animate-fade-in relative">
        <div className="absolute -top-24 left-1/2 -translate-x-1/2 w-64 h-64 bg-purple-600/10 rounded-full blur-[100px] pointer-events-none" />
        
        <div className="text-center relative flex flex-col items-center">
          <div className="w-20 h-20 rounded-3xl overflow-hidden shadow-2xl mb-6 bg-neutral-900 border border-white/5 flex items-center justify-center relative">
            <img 
              src="/logo.png" 
              alt="R.S Audio Logo" 
              className="w-full h-full object-cover z-10" 
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = 'none';
              }}
            />
            <Headphones size={32} className="text-purple-500 absolute" />
          </div>
          <h1 className="text-3xl font-black tracking-tighter text-purple-500 mb-2 drop-shadow-aether-glow leading-tight">R.S AUDIOBOOK PLAYER</h1>
          <div className="flex items-center justify-center gap-2">
            <Activity size={10} className="text-neutral-700" />
            <p className="text-neutral-700 uppercase tracking-[0.5em] text-[10px] font-black">Secure Link Portal</p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4 relative">
          <div className="relative group">
            <LinkIcon size={14} className="absolute left-5 top-1/2 -translate-y-1/2 text-neutral-800 group-focus-within:text-purple-500 transition-colors" />
            <input
              type="text"
              placeholder="SERVER ENDPOINT"
              value={serverUrl}
              onChange={(e) => setServerUrl(e.target.value)}
              className="w-full bg-neutral-900 border-none py-5 pl-14 pr-6 rounded-[24px] text-white placeholder-neutral-800 font-black text-xs tracking-widest outline-none focus:ring-1 focus:ring-purple-600/40 transition-all"
              required
            />
          </div>

          <div className="relative group">
            <User size={14} className="absolute left-5 top-1/2 -translate-y-1/2 text-neutral-800 group-focus-within:text-purple-500 transition-colors" />
            <input
              type="text"
              placeholder="USERNAME"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full bg-neutral-900 border-none py-5 pl-14 pr-6 rounded-[24px] text-white placeholder-neutral-800 font-black text-xs tracking-widest outline-none focus:ring-1 focus:ring-purple-600/40 transition-all"
              required
            />
          </div>

          <div className="relative group">
            <Lock size={14} className="absolute left-5 top-1/2 -translate-y-1/2 text-neutral-800 group-focus-within:text-purple-500 transition-colors" />
            <input
              type="password"
              placeholder="PASSWORD"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full bg-neutral-900 border-none py-5 pl-14 pr-6 rounded-[24px] text-white placeholder-neutral-800 font-black text-xs tracking-widest outline-none focus:ring-1 focus:ring-purple-600/40 transition-all"
              required
            />
          </div>

          {error && (
            <div className="bg-red-500/5 border border-red-500/20 p-6 rounded-[24px] text-center animate-shake">
              <div className="flex justify-center mb-2">
                <ShieldAlert size={20} className="text-red-500" />
              </div>
              <div className="text-red-500 text-[10px] font-black uppercase tracking-widest leading-relaxed">
                {error}
              </div>
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full gradient-aether py-6 rounded-[24px] font-black text-lg tracking-[0.2em] shadow-aether-glow active:scale-95 transition-all text-white mt-4 disabled:opacity-50 disabled:scale-100"
          >
            {loading ? 'AUTHENTICATING...' : 'CONNECT'}
          </button>
        </form>

        <div className="text-center pt-8">
          <p className="text-[8px] font-black text-neutral-800 uppercase tracking-[0.4em]">Proprietary Archive Technology • V5.2</p>
        </div>
      </div>
    </div>
  );
};

export default Login;
