// views/Player.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed } from 'vue';
import { AuthState, ABSLibraryItem } from '../types';
import { usePlayer } from '../composables/usePlayer';
import { ABSService } from '../services/absService';
import { OfflineManager } from '../services/offlineManager';
import ChapterEditor from '../components/ChapterEditor.vue';
import { 
  ChevronDown, Play, Pause, Info, X, SkipBack, SkipForward,
  RotateCcw, RotateCw, ChevronRight, Gauge, Moon, Plus, Minus, Mic, Clock, Layers, Download, CheckCircle, Loader2
} from 'lucide-vue-next';

const props = defineProps<{
  auth: AuthState,
  item: ABSLibraryItem
}>();

const emit = defineEmits<{
  (e: 'back'): void,
  (e: 'select-series', seriesId: string): void,
  (e: 'item-updated', updatedItem: ABSLibraryItem): void
}>();

const { state, load, play, pause, seek, setPlaybackRate, setSleepChapters, setSleepTimer, destroy } = usePlayer();
const absService = computed(() => new ABSService(props.auth.serverUrl, props.auth.user?.token || ''));

const showChapters = ref(false);
const showInfo = ref(false);
const isDownloaded = ref(false);
const isDownloading = ref(false);
const downloadProgress = ref(0);

const activeItem = computed(() => state.activeItem || props.item);

const coverUrl = computed(() => {
  const baseUrl = props.auth.serverUrl.replace(/\/api\/?$/, '').replace(/\/+$/, '');
  return `${baseUrl}/api/items/${activeItem.value.id}/cover?token=${props.auth.user?.token}`;
});

const isFinished = computed(() => {
  return activeItem.value?.userProgress?.isFinished || false;
});

const chapters = computed(() => {
  if (!activeItem.value?.media?.chapters) return [];
  return activeItem.value.media.chapters;
});

const currentChapterIndex = computed(() => {
  if (!chapters.value || chapters.value.length === 0) return -1;
  const time = state.currentTime + 0.1;
  return chapters.value.findIndex((ch, i) => 
    time >= ch.start && (i === chapters.value.length - 1 || time < (chapters[i+1]?.start || ch.end))
  );
});

const currentChapter = computed(() => currentChapterIndex.value !== -1 ? chapters.value[currentChapterIndex.value] : null);

// Chapter specific progress Math
const chapterProgressPercent = computed(() => {
  if (!currentChapter.value) return 0;
  const chapterDur = currentChapter.value.end - currentChapter.value.start;
  if (chapterDur <= 0) return 0;
  const elapsed = state.currentTime - currentChapter.value.start;
  return Math.max(0, Math.min(100, (elapsed / chapterDur) * 100));
});

// Effective time remaining considers playback speed
const chapterTimeRemaining = computed(() => {
  if (!currentChapter.value) return 0;
  const rawRemaining = Math.max(0, currentChapter.value.end - state.currentTime);
  return rawRemaining / state.playbackRate;
});

const bookProgressPercent = computed(() => {
  if (state.duration <= 0) return 0;
  return (state.currentTime / state.duration) * 100;
});

// Sleep Timer: Calculate total time until zzz
const sleepTimeRemaining = computed(() => {
  // 1. Check time-based timer first (Reactive via currentRealtime)
  if (state.sleepEndTime) {
    const remaining = Math.max(0, state.sleepEndTime - state.currentRealtime) / 1000;
    return remaining > 0 ? remaining : 0;
  }

  // 2. Fallback to Chapter-based timer
  if (state.sleepChapters <= 0 || currentChapterIndex.value === -1) return 0;
  
  let totalTime = Math.max(0, (currentChapter.value?.end || 0) - state.currentTime);
  const nextChaptersCount = state.sleepChapters - 1;
  for (let i = 1; i <= nextChaptersCount; i++) {
    const nextIdx = currentChapterIndex.value + i;
    const ch = chapters.value[nextIdx];
    if (ch) {
      totalTime += (ch.end - ch.start);
    }
  }
  
  return totalTime / state.playbackRate;
});

const secondsToTimestamp = (s: number) => {
  if (isNaN(s) || s < 0) return "00:00";
  const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), sec = Math.floor(s % 60);
  return `${h > 0 ? h + ':' : ''}${m.toString().padStart(h > 0 ? 2 : 1, '0')}:${sec.toString().padStart(2, '0')}`;
};

onMounted(async () => {
  load(props.item, props.auth);
  checkDownloadStatus();
});

const checkDownloadStatus = async () => {
  if (activeItem.value?.id) {
    isDownloaded.value = await OfflineManager.isDownloaded(activeItem.value.id);
  }
};

onUnmounted(() => {
  destroy();
});

const togglePlay = () => state.isPlaying ? pause() : play();

const skipToNextChapter = () => {
  if (currentChapterIndex.value === -1 || currentChapterIndex.value >= chapters.value.length - 1) return;
  const next = chapters.value[currentChapterIndex.value + 1];
  seek(next.start);
};

const skipToPrevChapter = () => {
  if (currentChapterIndex.value <= 0) {
    seek(0);
    return;
  }
  if (state.currentTime - (currentChapter.value?.start || 0) > 4) {
    seek(currentChapter.value!.start);
  } else {
    const prev = chapters.value[currentChapterIndex.value - 1];
    seek(prev.start);
  }
};

const handleChapterSeek = (time: number) => {
  seek(time);
};

const handleChapterProgressClick = (e: MouseEvent) => {
  if (!currentChapter.value) return;
  const el = e.currentTarget as HTMLElement;
  const rect = el.getBoundingClientRect();
  const ratio = (e.clientX - rect.left) / rect.width;
  const chapterDur = currentChapter.value.end - currentChapter.value.start;
  const targetTime = currentChapter.value.start + (ratio * chapterDur);
  seek(targetTime);
};

const adjustSleepTimer = (count: number) => {
  setSleepChapters(state.sleepChapters + count);
};

const handleSeriesClick = (e: Event) => {
  e.stopPropagation(); // Explicitly prevent propagation
  if (metadata.value.seriesId) {
    emit('select-series', metadata.value.seriesId);
    showInfo.value = false;
  }
};

const handleToggleDownload = async () => {
  if (isDownloading.value) return;
  
  if (isDownloaded.value) {
    if (confirm("Remove download from local storage?")) {
      await OfflineManager.removeBook(activeItem.value.id);
      isDownloaded.value = false;
    }
  } else {
    isDownloading.value = true;
    downloadProgress.value = 0;
    try {
      await OfflineManager.saveBook(absService.value, activeItem.value, (pct) => {
        downloadProgress.value = pct;
      });
      isDownloaded.value = true;
    } catch (e) {
      console.error("Download failed", e);
      alert("Failed to download artifact.");
    } finally {
      isDownloading.value = false;
      downloadProgress.value = 0;
    }
  }
};

const metadata = computed(() => activeItem.value?.media?.metadata || {});

const infoRows = computed(() => {
  return [
    { label: 'Narrator', value: metadata.value.narratorName || 'Unknown', icon: Mic },
    { label: 'Series', value: metadata.value.seriesName || 'Standalone', icon: Layers, isClickable: !!metadata.value.seriesId },
    { label: 'Duration', value: secondsToTimestamp(state.duration), icon: Clock },
    { label: 'Year', value: metadata.value.publishedYear || 'Unknown', icon: Clock }
  ];
});
</script>

<template>
  <div class="h-[100dvh] w-full bg-[#0d0d0d] text-white flex flex-col relative overflow-hidden font-sans select-none safe-top safe-bottom">
    <div class="absolute inset-0 z-0 pointer-events-none flex items-center justify-center">
      <div class="w-[500px] h-[500px] bg-purple-600/10 rounded-full blur-[160px] animate-pulse" />
    </div>

    <Transition name="fade">
      <div v-if="state.isLoading" class="absolute inset-0 bg-[#0d0d0d] flex flex-col items-center justify-center gap-6 z-[100]">
        <div class="w-12 h-12 border-2 border-purple-600/10 border-t-purple-600 rounded-full animate-spin" />
        <p class="text-[8px] font-black uppercase tracking-[0.6em] text-neutral-600">Establishing Archive Stream...</p>
      </div>
    </Transition>

    <template v-if="!state.isLoading">
      <!-- Top Navigation Header -->
      <header class="px-8 py-6 md:py-8 flex justify-between items-center z-20 shrink-0">
        <button @click="emit('back')" class="p-2 text-neutral-600 hover:text-white transition-colors active:scale-90">
          <ChevronDown :size="24" stroke-width="1.5" />
        </button>
        <button @click="showChapters = true" class="flex flex-col items-center gap-1 group">
          <span class="text-[7px] font-black uppercase tracking-[0.5em] text-neutral-700 group-hover:text-purple-500 transition-colors">CHAPTER INDEX</span>
          <div class="flex items-center gap-2 max-w-[200px]">
            <span class="text-[10px] font-black uppercase tracking-widest text-neutral-300 truncate">{{ currentChapter?.title || 'Segment 01' }}</span>
            <ChevronRight :size="12" class="text-neutral-700" />
          </div>
        </button>
        <div class="flex items-center gap-2">
          <!-- Download Button with Progress -->
          <button @click="handleToggleDownload" class="p-2 relative transition-colors group" :class="isDownloaded ? 'text-purple-500' : 'text-neutral-600 hover:text-purple-400'">
            <div v-if="isDownloading" class="absolute inset-0 flex items-center justify-center">
               <svg class="w-full h-full -rotate-90" viewBox="0 0 36 36">
                 <path class="text-neutral-800" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" stroke-width="4" />
                 <path class="text-purple-500 transition-all duration-200" :stroke-dasharray="downloadProgress + ', 100'" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" stroke-width="4" />
               </svg>
            </div>
            <CheckCircle v-else-if="isDownloaded" :size="22" stroke-width="1.5" />
            <Download v-else :size="22" stroke-width="1.5" />
          </button>

          <button @click="showInfo = true" class="p-2 text-neutral-600 hover:text-white transition-colors">
            <Info :size="22" stroke-width="1.5" />
          </button>
        </div>
      </header>

      <!-- Main Split Layout -->
      <!-- Flex Col for Mobile, Row for Desktop/Landscape -->
      <div class="flex-1 w-full h-full flex flex-col lg:flex-row overflow-hidden relative z-10">
        
        <!-- Left Column: Visuals & Metadata (40% Desktop) -->
        <div class="flex-1 lg:flex-none lg:w-[40%] flex flex-col items-center justify-center px-8 pb-4 lg:pb-0 relative z-10 min-h-0">
          <!-- Book Cover - Formatted as a Book (2:3 aspect) -->
          <div @click="showInfo = true" class="relative w-full max-w-[260px] md:max-w-[340px] aspect-[2/3] group cursor-pointer perspective-1000 shrink-0 mb-6 lg:mb-10 max-h-[50vh] lg:max-h-none">
            <div class="absolute -inset-10 bg-purple-600/5 blur-[100px] rounded-full opacity-50" />
            
            <div class="relative z-10 w-full h-full rounded-r-2xl rounded-l-sm overflow-hidden border-t border-r border-b border-white/10 shadow-[20px_20px_60px_-15px_rgba(0,0,0,0.8)] transition-transform duration-700 group-hover:scale-[1.02] group-hover:-translate-y-2 book-spine">
               <!-- Spine Highlight -->
               <div class="absolute left-0 top-0 bottom-0 w-1.5 bg-gradient-to-r from-white/20 to-transparent z-20" />
               <div class="absolute left-1.5 top-0 bottom-0 w-px bg-black/40 z-20" />

               <img :src="coverUrl" class="w-full h-full object-contain bg-black" />
            </div>
          </div>

          <div class="text-center space-y-4 w-full max-w-md px-4 z-10">
            <!-- Updated Typography for Metadata -->
            <div class="space-y-2">
              <div class="flex items-center justify-center gap-3">
                <h1 class="text-2xl md:text-3xl font-black uppercase tracking-tight text-white leading-tight line-clamp-2" :title="metadata.title">
                  {{ metadata.title }}
                </h1>
                <CheckCircle v-if="isFinished" class="text-green-500 shrink-0" :size="24" fill="currentColor" stroke-width="2" stroke="black" />
              </div>
              <p class="text-lg font-bold text-neutral-500 line-clamp-1">
                {{ metadata.authorName }}
              </p>
            </div>
            
            <!-- Series Link (Visible and Clickable) - Moved/Styled as requested -->
            <button 
              v-if="metadata.seriesName" 
              @click="handleSeriesClick($event)"
              class="text-purple-400 font-semibold block mt-2 hover:text-purple-300 transition-colors text-sm uppercase tracking-widest truncate max-w-full mx-auto px-4 py-1.5 rounded-full bg-white/5 hover:bg-white/10 border border-white/5"
            >
              {{ metadata.seriesName }} {{ metadata.seriesSequence ? `#${metadata.seriesSequence}` : '' }}
            </button>
          </div>
        </div>

        <!-- Right Column: Controls (60% Desktop) -->
        <div class="shrink-0 lg:flex-1 lg:w-[60%] lg:h-full flex flex-col justify-end lg:justify-center px-8 pb-12 lg:pb-0 lg:px-24 space-y-10 lg:space-y-16 w-full max-w-xl lg:max-w-3xl mx-auto lg:mx-0 z-20">
          
          <!-- Progress Area -->
          <div class="space-y-4">
            <div class="flex justify-between items-end mb-1">
               <div class="flex flex-col">
                 <span class="text-[8px] font-black text-neutral-600 uppercase tracking-widest">Chapter Elapsed</span>
                 <span class="text-lg font-black font-mono-timer tabular-nums tracking-tighter text-white">{{ secondsToTimestamp(state.currentTime - (currentChapter?.start || 0)) }}</span>
               </div>
               <div class="flex flex-col items-end">
                 <span class="text-[8px] font-black text-neutral-600 uppercase tracking-widest">Chapter Remaining</span>
                 <span class="text-lg font-black font-mono-timer tabular-nums tracking-tighter text-purple-500">-{{ secondsToTimestamp(chapterTimeRemaining) }}</span>
               </div>
            </div>

            <!-- Interactive Chapter Progress Bar -->
            <div 
              class="h-3 w-full bg-neutral-900 rounded-full relative overflow-hidden shadow-inner border border-white/5 cursor-pointer"
              @click="handleChapterProgressClick"
            >
              <div 
                class="h-full bg-purple-600 shadow-[0_0_20px_rgba(168,85,247,0.6)] transition-all duration-300 rounded-r-full" 
                :style="{ width: chapterProgressPercent + '%' }"
              />
            </div>

            <!-- Secondary Global Progress Bar -->
            <div class="h-1 w-full bg-neutral-900/40 rounded-full relative overflow-hidden border border-white/5 pointer-events-none">
              <div class="h-full bg-neutral-600/50 transition-all duration-150" :style="{ width: bookProgressPercent + '%' }" />
            </div>
          </div>

          <!-- Controls -->
          <div class="flex items-center justify-center gap-4 md:gap-8">
            <button @click="skipToPrevChapter" class="p-3 text-neutral-700 hover:text-purple-400 transition-colors active:scale-90"><SkipBack :size="20" /></button>
            <button @click="seek(state.currentTime - 10)" class="p-3 text-neutral-700 hover:text-white transition-colors active:scale-90"><RotateCcw :size="24" /></button>
            <button @click="togglePlay" class="w-20 h-20 rounded-full bg-purple-600/10 flex items-center justify-center border border-purple-500/20 shadow-[0_0_50px_rgba(157,80,187,0.1)] active:scale-95 transition-all group relative">
              <Pause v-if="state.isPlaying" :size="32" class="text-purple-500 fill-current" />
              <Play v-else :size="32" class="text-purple-500 fill-current translate-x-1" />
            </button>
            <button @click="seek(state.currentTime + 30)" class="p-3 text-neutral-700 hover:text-white transition-colors active:scale-90"><RotateCw :size="24" /></button>
            <button @click="skipToNextChapter" class="p-3 text-neutral-700 hover:text-purple-400 transition-colors active:scale-90"><SkipForward :size="20" /></button>
          </div>

          <!-- Speed & Sleep -->
          <div class="grid grid-cols-2 gap-4">
            <div class="bg-neutral-900/40 border border-white/5 rounded-[24px] p-5 flex flex-col items-center gap-4 hover:border-white/10 transition-colors">
              <div class="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500"><Gauge :size="12" /><span>Speed</span></div>
              <div class="flex items-center justify-between w-full px-2">
                <button @click="setPlaybackRate(Math.max(0.5, state.playbackRate - 0.1))" class="p-1 text-neutral-600 hover:text-white"><Minus :size="14" /></button>
                <span class="text-base font-black font-mono text-white">{{ state.playbackRate.toFixed(1) }}x</span>
                <button @click="setPlaybackRate(Math.min(2.5, state.playbackRate + 0.1))" class="p-1 text-neutral-600 hover:text-white"><Plus :size="14" /></button>
              </div>
            </div>
            
            <div class="bg-neutral-900/40 border border-white/5 rounded-[24px] p-5 flex flex-col items-center gap-3 hover:border-white/10 transition-colors">
              <!-- Header Row -->
              <div class="flex items-center justify-between w-full px-1">
                <div class="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500"><Moon :size="12" /><span>Sleep</span></div>
                
                <!-- Quick Timers moved here -->
                <div class="flex gap-2">
                   <button 
                    @click="setSleepTimer(900)" 
                    class="text-[10px] font-bold px-1.5 py-0.5 rounded border border-neutral-800 text-neutral-500 hover:text-white hover:border-neutral-600 transition-all"
                    :class="{ 'text-purple-400 border-purple-500/30': state.sleepEndTime && (state.sleepEndTime - state.currentRealtime) <= 900000 && (state.sleepEndTime - state.currentRealtime) > 0 }"
                   >15m</button>
                   <button 
                    @click="setSleepTimer(1800)" 
                    class="text-[10px] font-bold px-1.5 py-0.5 rounded border border-neutral-800 text-neutral-500 hover:text-white hover:border-neutral-600 transition-all"
                    :class="{ 'text-purple-400 border-purple-500/30': state.sleepEndTime && (state.sleepEndTime - state.currentRealtime) > 900000 }"
                   >30m</button>
                </div>
              </div>

              <!-- Main Control -->
              <div class="flex items-center justify-between w-full px-2 mt-1">
                <button @click="adjustSleepTimer(-1)" class="p-1 text-neutral-600 hover:text-white"><Minus :size="14" /></button>
                <div class="flex flex-col items-center min-w-[60px]">
                   <span v-if="state.sleepChapters > 0 || state.sleepEndTime" class="text-xs font-black text-purple-400 tracking-tighter text-center leading-none">
                     {{ state.sleepChapters > 0 ? `${state.sleepChapters} ch` : 'Time' }}
                   </span>
                   <span v-if="state.sleepChapters > 0 || state.sleepEndTime" class="text-sm font-black font-mono text-white mt-1 drop-shadow-md">{{ secondsToTimestamp(sleepTimeRemaining) }}</span>
                   <span v-else class="text-sm font-black font-mono text-neutral-600 uppercase">OFF</span>
                </div>
                <button @click="adjustSleepTimer(1)" class="p-1 text-neutral-600 hover:text-white"><Plus :size="14" /></button>
              </div>
            </div>
          </div>

        </div>
      </div>
    </template>

    <ChapterEditor 
      v-if="showChapters" 
      :item="activeItem" 
      :currentTime="state.currentTime"
      :isPlaying="state.isPlaying"
      @close="showChapters = false"
      @seek="handleChapterSeek"
    />

    <!-- Info Sheet -->
    <Transition name="slide-up">
      <div v-if="showInfo" class="fixed inset-0 bg-black/95 backdrop-blur-3xl z-[160] flex flex-col">
        <header class="p-10 flex justify-between items-center bg-transparent shrink-0">
          <div class="space-y-1">
            <h2 class="text-xl font-black uppercase tracking-tighter text-white">ARTIFACT DETAILS</h2>
            <p class="text-[8px] font-black uppercase tracking-[0.5em] text-purple-700">Registry Inventory Record</p>
          </div>
          <button @click="showInfo = false" class="p-4 bg-neutral-900/50 rounded-full text-neutral-500 hover:text-white border border-white/5 transition-all"><X :size="20"/></button>
        </header>
        <div class="flex-1 overflow-y-auto p-10 space-y-12 max-w-2xl mx-auto w-full no-scrollbar pb-32">
          <div class="space-y-4">
            <div class="flex items-center gap-2 text-neutral-700"><Layers :size="14" /><span class="text-[9px] font-black uppercase tracking-[0.4em]">Artifact Summary</span></div>
            <h3 class="text-3xl font-black uppercase tracking-tighter text-white leading-tight">{{ metadata.title }}</h3>
            <p class="text-neutral-500 text-sm leading-relaxed">{{ metadata.description || 'No summary retrieved from repository.' }}</p>
          </div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-8 border-t border-white/5 pt-12">
            <div v-for="row in infoRows" :key="row.label" class="flex flex-col gap-2">
              <div class="flex items-center gap-2 text-neutral-500"><component :is="row.icon" :size="12" /><span class="text-[9px] font-black uppercase tracking-[0.4em]">{{ row.label }}</span></div>
              <template v-if="row.isClickable"><button @click="handleSeriesClick($event)" class="text-left text-sm font-bold text-white hover:text-purple-400 transition-colors cursor-pointer w-fit py-1 px-3 bg-purple-600/10 border border-purple-500/20 rounded-full active:scale-95">{{ row.value }}</button></template>
              <template v-else><span class="text-sm font-bold text-white">{{ row.value }}</span></template>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </div>
</template>

<style scoped>
.fade-enter-active, .fade-leave-active { transition: opacity 0.4s ease; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
.slide-up-enter-active, .slide-up-leave-active { transition: transform 0.6s cubic-bezier(0.22, 1, 0.36, 1); }
.slide-up-enter-from, .slide-up-leave-to { transform: translateY(100%); }

.perspective-1000 {
  perspective: 1000px;
}
.book-spine {
  border-left: 2px solid rgba(255,255,255,0.1);
  box-shadow: 
    inset 10px 0 20px rgba(0,0,0,0.5),
    10px 10px 30px rgba(0,0,0,0.5);
}

.shadow-aether-glow {
  text-shadow: 0 0 10px rgba(168, 85, 247, 0.6);
}
</style>

// components/Player.tsx
import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { AuthState, ABSLibraryItem, ABSChapter } from '../types';
import { ABSService } from '../services/absService';
import Hls from 'hls.js';
import { ChevronDown, Play, Pause, SkipBack, SkipForward, Timer, Info, X, Activity, Plus, Minus, AlertCircle, RotateCcw, RotateCw } from 'lucide-react';

interface PlayerProps {
  auth: AuthState;
  item: ABSLibraryItem;
  onBack: () => void;
}

const Player: React.FC<PlayerProps> = ({ auth, item, onBack }) => {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const syncIntervalRef = useRef<number | null>(null);
  const hlsRef = useRef<Hls | null>(null);
  const isMounted = useRef(true);
  const loadTimeoutRef = useRef<number | null>(null);
  const sleepIntervalRef = useRef<number | null>(null);
  
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [chapters, setChapters] = useState<ABSChapter[]>([]);
  const [showChapters, setShowChapters] = useState(false);
  const [showInfo, setShowInfo] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [playbackSpeed, setPlaybackSpeed] = useState(1.0);
  
  // Sleep Timer in Seconds
  const [sleepSeconds, setSleepSeconds] = useState<number>(0);

  const absService = useMemo(() => new ABSService(auth.serverUrl, auth.user?.token || ''), [auth]);
  const duration = item.media.duration || 0;
  const coverUrl = useMemo(() => absService.getCoverUrl(item.id), [item.id, absService]);

  const currentChapterIndex = useMemo(() => {
    if (!chapters.length) return -1;
    return chapters.findIndex((ch, i) => 
      currentTime >= ch.start && (i === chapters.length - 1 || currentTime < (chapters[i+1]?.start || ch.end))
    );
  }, [chapters, currentTime]);

  const currentChapter = useMemo(() => currentChapterIndex !== -1 ? chapters[currentChapterIndex] : null, [chapters, currentChapterIndex]);
  const chapterRemaining = currentChapter ? Math.max(0, currentChapter.end - currentTime) : 0;
  const chapterProgress = currentChapter ? ((currentTime - currentChapter.start) / (currentChapter.end - currentChapter.start)) * 100 : 0;

  // Sleep Timer Countdown Logic
  useEffect(() => {
    if (isPlaying && sleepSeconds > 0) {
      sleepIntervalRef.current = window.setInterval(() => {
        setSleepSeconds(prev => {
          if (prev <= 1) {
            if (audioRef.current) audioRef.current.pause();
            setIsPlaying(false);
            if (sleepIntervalRef.current) clearInterval(sleepIntervalRef.current);
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    } else {
      if (sleepIntervalRef.current) clearInterval(sleepIntervalRef.current);
    }
    return () => { if (sleepIntervalRef.current) clearInterval(sleepIntervalRef.current); };
  }, [isPlaying, sleepSeconds]);

  const togglePlay = useCallback(async () => {
    if (!audioRef.current || isLoading || error) return;
    try {
      if (audioRef.current.paused) {
        await audioRef.current.play();
        setIsPlaying(true);
      } else {
        audioRef.current.pause();
        setIsPlaying(false);
      }
    } catch (err) {
      console.error("Playback toggle failed", err);
    }
  }, [isLoading, error]);

  const skipChapter = useCallback((direction: number) => {
    if (!chapters.length || !audioRef.current) return;
    const targetIdx = Math.max(0, Math.min(chapters.length - 1, currentChapterIndex + direction));
    audioRef.current.currentTime = chapters[targetIdx].start;
    setCurrentTime(chapters[targetIdx].start);
  }, [chapters, currentChapterIndex]);

  const setupMediaSession = useCallback(() => {
    if ('mediaSession' in navigator) {
      navigator.mediaSession.metadata = new MediaMetadata({
        title: item.media.metadata.title,
        artist: item.media.metadata.authorName,
        album: item.media.metadata.seriesName || 'R.S Audio',
        artwork: [{ src: coverUrl, sizes: '512x512', type: 'image/png' }]
      });

      navigator.mediaSession.setActionHandler('play', togglePlay);
      navigator.mediaSession.setActionHandler('pause', togglePlay);
      navigator.mediaSession.setActionHandler('seekbackward', () => { if(audioRef.current) audioRef.current.currentTime -= 15; });
      navigator.mediaSession.setActionHandler('seekforward', () => { if(audioRef.current) audioRef.current.currentTime += 30; });
      navigator.mediaSession.setActionHandler('previoustrack', () => skipChapter(-1));
      navigator.mediaSession.setActionHandler('nexttrack', () => skipChapter(1));
    }
  }, [item, coverUrl, togglePlay, skipChapter]);

  useEffect(() => {
    isMounted.current = true;
    
    const init = async () => {
      setError(null);
      setIsLoading(true);

      loadTimeoutRef.current = window.setTimeout(() => {
        if (isLoading && isMounted.current) {
          setError('Unable to stream from server. Link timed out.');
          setIsLoading(false);
          if (hlsRef.current) hlsRef.current.destroy();
        }
      }, 10000);

      try {
        const [details] = await Promise.all([
          absService.getItemDetails(item.id),
        ]);

        if (!isMounted.current) return;
        if (!details) throw new Error("Unable to fetch item metadata.");

        setChapters(details.media.chapters || []);
        
        let progress = details.userProgress;
        if (!progress) {
          try {
            progress = await absService.getProgress(item.id);
          } catch (e) {
            console.warn("Failed to fetch progress, defaulting to zero.", e);
          }
        }
        
        const startAt = progress?.currentTime || 0;
        const audio = audioRef.current;
        if (audio) {
          audio.crossOrigin = 'anonymous';
          
          // Use the service helper for the requested HLS URL format
          const hlsUrl = absService.getHlsStreamUrl(item.id);
          
          if (Hls.isSupported()) {
            if (hlsRef.current) hlsRef.current.destroy();
            
            const hls = new Hls({ 
              enableWorker: true,
              maxBufferLength: 15,
              maxMaxBufferLength: 30,
              startPosition: startAt,
              autoStartLoad: true,
              lowLatencyMode: true,
              backBufferLength: 60,
              manifestLoadingMaxRetry: 5,
              levelLoadingMaxRetry: 5,
              // VITAL for cross-domain streaming with credentials
              xhrSetup: (xhr) => { xhr.withCredentials = true; }
            });
            
            hlsRef.current = hls;
            hls.attachMedia(audio);
            
            hls.on(Hls.Events.MEDIA_ATTACHED, () => {
              hls.loadSource(hlsUrl);
            });
            
            hls.on(Hls.Events.MANIFEST_PARSED, () => {
              if (isMounted.current) {
                if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
                setIsLoading(false);
              }
            });

            hls.on(Hls.Events.ERROR, (_, data) => {
              if (data.fatal) {
                if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
                switch (data.type) {
                  case Hls.ErrorTypes.NETWORK_ERROR:
                    hls.startLoad();
                    break;
                  case Hls.ErrorTypes.MEDIA_ERROR:
                    hls.recoverMediaError();
                    break;
                  default:
                    if (isMounted.current) {
                      setError("Unable to stream from server. Link failed.");
                      hls.destroy();
                      setIsLoading(false);
                    }
                    break;
                }
              }
            });
          } else if (audio.canPlayType('application/vnd.apple.mpegurl')) {
            audio.src = hlsUrl;
            const onCanPlay = () => {
              if (isMounted.current) {
                if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
                audio.currentTime = startAt;
                setCurrentTime(startAt);
                setIsLoading(false);
              }
              audio.removeEventListener('canplay', onCanPlay);
            };
            audio.addEventListener('canplay', onCanPlay);
            audio.addEventListener('error', () => {
              if (isMounted.current) {
                if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
                setError("Unable to stream from server. Native decoder failed.");
                setIsLoading(false);
              }
            }, { once: true });
          } else {
            throw new Error("HLS playback is not supported in this environment.");
          }

          setupMediaSession();
        }
      } catch (e: any) { 
        if (isMounted.current) {
          if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
          setError(e.message || "Unable to stream from server.");
          setIsLoading(false);
        }
      }
    };

    init();

    return () => { 
      isMounted.current = false;
      if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
      if (hlsRef.current) hlsRef.current.destroy();
    };
  }, [item.id, absService, auth]);

  const saveProgress = useCallback(() => {
    if (audioRef.current && audioRef.current.currentTime > 0) {
      absService.saveProgress(item.id, audioRef.current.currentTime, duration);
    }
  }, [item.id, duration, absService]);

  useEffect(() => {
    if (isPlaying) syncIntervalRef.current = window.setInterval(saveProgress, 10000);
    return () => { 
      if (syncIntervalRef.current) clearInterval(syncIntervalRef.current); 
      saveProgress(); 
    };
  }, [isPlaying, saveProgress]);

  useEffect(() => {
    if (audioRef.current) audioRef.current.playbackRate = playbackSpeed;
  }, [playbackSpeed]);

  const formatTime = (s: number) => {
    if (isNaN(s)) return "00:00";
    const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), sec = Math.floor(s % 60);
    return `${h > 0 ? h + ':' : ''}${m.toString().padStart(h > 0 ? 2 : 1, '0')}:${sec.toString().padStart(2, '0')}`;
  };

  const handleAdjustSleep = (mins: number) => {
    setSleepSeconds(prev => Math.max(0, prev + (mins * 60)));
  };

  if (isLoading) return (
    <div className="h-[100dvh] flex flex-col items-center justify-center bg-black gap-4 z-50">
      <div className="w-12 h-12 border-4 border-purple-600/20 border-t-purple-600 rounded-full animate-spin" />
      <p className="text-[10px] font-black uppercase tracking-[0.4em] text-neutral-800">Establishing Archive Link...</p>
      <button onClick={onBack} className="mt-8 text-[10px] font-black uppercase tracking-widest text-neutral-500 underline">Abort Sync</button>
    </div>
  );

  if (error) return (
    <div className="h-[100dvh] flex flex-col items-center justify-center bg-black p-10 gap-6 text-center">
      <AlertCircle size={48} className="text-red-500 animate-pulse" />
      <div className="space-y-2">
        <h2 className="text-lg font-black uppercase tracking-tighter text-white">Archive Link Severed</h2>
        <p className="text-[10px] font-black uppercase tracking-widest text-neutral-500">{error}</p>
      </div>
      <button onClick={() => window.location.reload()} className="px-10 py-4 bg-purple-600 rounded-full font-black uppercase text-[10px] tracking-[0.3em] active:scale-95 transition-all shadow-lg">Retry Portal</button>
      <button onClick={onBack} className="text-[10px] font-black uppercase tracking-widest text-neutral-700 hover:text-white transition-colors">Return to Library</button>
    </div>
  );

  return (
    <div className="h-[100dvh] w-full bg-black text-white flex flex-col relative overflow-hidden font-sans select-none">
      <audio 
        ref={audioRef} 
        onTimeUpdate={e => setCurrentTime(e.currentTarget.currentTime)} 
        onPlay={() => setIsPlaying(true)}
        onPause={() => setIsPlaying(false)}
        onEnded={() => setIsPlaying(false)} 
        preload="auto"
        crossOrigin="anonymous"
      />
      
      <header className="px-8 pt-10 pb-4 flex justify-between items-center z-20 shrink-0">
        <button onClick={onBack} className="text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500 bg-neutral-900/40 px-4 py-2 rounded-full border border-white/5 active:scale-95 transition-all">Archive Exit</button>
        <button onClick={() => setShowChapters(true)} className="flex items-center gap-2 bg-neutral-900/60 px-4 py-2 rounded-full border border-white/5 group active:scale-95 transition-all max-w-[50%]">
          <span className="text-[9px] font-black uppercase tracking-[0.2em] text-purple-500 truncate">{currentChapter?.title || 'Index'}</span>
          <ChevronDown size={14} className="text-purple-500 flex-shrink-0" />
        </button>
      </header>

      <div className="flex-1 flex flex-col items-center justify-between px-8 py-4 overflow-hidden">
        <div className="flex-1 w-full flex items-center justify-center mb-6 relative">
          <button onClick={() => setShowInfo(true)} className="aspect-square w-full max-w-[320px] relative group active:scale-95 transition-all shadow-2xl">
            <img src={coverUrl} className="w-full h-full object-cover rounded-[56px] border border-white/10" alt="" />
            <div className="absolute top-6 right-6 p-3 rounded-full bg-black/40 backdrop-blur-xl border border-white/10 opacity-0 group-hover:opacity-100 transition-opacity">
              <Info size={18} className="text-white" />
            </div>
            {sleepSeconds > 0 && (
               <div className="absolute top-6 left-6 flex items-center gap-2 bg-purple-600/90 backdrop-blur-md px-4 py-2 rounded-full border border-white/10 shadow-2xl">
                 <Timer size={14} className="text-white" />
                 <span className="text-[10px] font-black font-mono text-white">{formatTime(sleepSeconds)}</span>
               </div>
            )}
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent rounded-[56px]" />
          </button>
        </div>

        <div className="w-full space-y-6 shrink-0 pb-8 max-w-xl mx-auto">
          <div className="flex flex-col items-center justify-center text-center w-full px-4 space-y-2">
            {item.media.metadata.seriesName && (
              <div className="px-3 py-1 rounded-full bg-neutral-900 border border-white/10 mb-1">
                <span className="text-[9px] font-black uppercase tracking-widest text-neutral-400">{item.media.metadata.seriesName} #{item.media.metadata.sequence}</span>
              </div>
            )}
            <h1 className="text-2xl md:text-3xl font-black uppercase tracking-tighter leading-tight line-clamp-1 w-full">{item.media.metadata.title}</h1>
            <p className="text-neutral-500 text-[10px] font-black uppercase tracking-[0.3em]">{item.media.metadata.authorName}</p>
          </div>

          <div className="flex justify-between items-center px-4">
             <div className="flex flex-col items-start">
               <span className="text-[8px] font-black text-neutral-700 uppercase tracking-widest mb-1">Chapter End</span>
               <span className="text-xs font-mono font-bold text-purple-500">-{formatTime(chapterRemaining)}</span>
             </div>
             <div className="flex flex-col items-end">
               <span className="text-[8px] font-black text-neutral-700 uppercase tracking-widest mb-1">Total Rem.</span>
               <span className="text-xs font-mono font-bold text-neutral-500">{formatTime(duration - currentTime)}</span>
             </div>
          </div>

          <div className="px-2">
            <div className="h-1.5 w-full bg-neutral-900 rounded-full relative overflow-hidden">
              <div className="h-full gradient-aether shadow-aether-glow transition-all duration-300" style={{ width: `${chapterProgress}%` }} />
            </div>
            <div className="flex justify-between mt-3 px-1">
              <span className="text-[9px] font-black text-neutral-700 uppercase tracking-widest truncate max-w-[70%]">{currentChapter?.title || 'Reading...'}</span>
              <span className="text-[9px] font-black text-neutral-700 tabular-nums">{Math.round(chapterProgress)}%</span>
            </div>
          </div>

          <div className="flex items-center justify-center gap-6 md:gap-10 w-full py-4">
            <button onClick={() => { if(audioRef.current) audioRef.current.currentTime -= 15; }} className="p-4 text-neutral-400 hover:text-white transition-all active:scale-75 flex flex-col items-center gap-1">
              <RotateCcw size={28} />
              <span className="text-[8px] font-black">15s</span>
            </button>
            <button onClick={togglePlay} className="w-20 h-20 md:w-24 md:h-24 gradient-aether rounded-full flex items-center justify-center shadow-lg active:scale-95 transition-all">
              {isPlaying ? <Pause size={38} className="text-white fill-current" /> : <Play size={38} className="text-white fill-current translate-x-1" />}
            </button>
            <button onClick={() => { if(audioRef.current) audioRef.current.currentTime += 30; }} className="p-4 text-neutral-400 hover:text-white transition-all active:scale-75 flex flex-col items-center gap-1">
              <RotateCw size={28} />
              <span className="text-[8px] font-black">30s</span>
            </button>
          </div>

          <div className="grid grid-cols-2 gap-4 pb-2">
            <div className="bg-neutral-900/40 rounded-[32px] p-5 flex flex-col items-center justify-center border border-white/5 backdrop-blur-md">
              <span className="text-[8px] font-black text-neutral-700 uppercase tracking-[0.2em] mb-3">Sync Speed</span>
              <div className="flex items-center gap-6">
                <button onClick={() => setPlaybackSpeed(s => Math.max(0.5, s - 0.1))} className="w-10 h-10 flex items-center justify-center bg-black/40 rounded-full text-neutral-400 hover:text-white active:scale-90 transition-all border border-white/5"><Minus size={16} /></button>
                <span className="text-xs font-black text-purple-500 tracking-widest font-mono">{playbackSpeed.toFixed(1)}x</span>
                <button onClick={() => setPlaybackSpeed(s => Math.min(2.5, s + 0.1))} className="w-10 h-10 flex items-center justify-center bg-black/40 rounded-full text-neutral-400 hover:text-white active:scale-90 transition-all border border-white/5"><Plus size={16} /></button>
              </div>
            </div>

            <div className={`bg-neutral-900/40 rounded-[32px] p-5 flex flex-col items-center justify-center border transition-all backdrop-blur-md ${sleepSeconds > 0 ? 'border-purple-600/40 bg-purple-600/5' : 'border-white/5'}`}>
              <div className="flex items-center gap-2 mb-2">
                <Timer size={10} className={sleepSeconds > 0 ? 'text-purple-500' : 'text-neutral-700'} />
                <span className={`text-[8px] font-black uppercase tracking-[0.2em] ${sleepSeconds > 0 ? 'text-purple-500' : 'text-neutral-700'}`}>Sleep Timer</span>
              </div>
              <div className="flex items-center gap-6">
                <button onClick={() => handleAdjustSleep(-5)} className="w-10 h-10 flex items-center justify-center bg-black/40 rounded-full text-neutral-400 hover:text-white active:scale-90 transition-all border border-white/5"><Minus size={16} /></button>
                <div className="flex flex-col items-center justify-center min-w-[50px]">
                  <span className="text-xs font-black text-white tracking-widest font-mono">{sleepSeconds === 0 ? 'OFF' : formatTime(sleepSeconds)}</span>
                  {sleepSeconds > 0 && <span className="text-[7px] font-black text-purple-500 uppercase tracking-widest mt-0.5">Suspension</span>}
                </div>
                <button onClick={() => handleAdjustSleep(15)} className="w-10 h-10 flex items-center justify-center bg-black/40 rounded-full text-neutral-400 hover:text-white active:scale-90 transition-all border border-white/5"><Plus size={16} /></button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {showChapters && (
        <div className="fixed inset-0 z-[100] animate-fade-in flex flex-col bg-black">
          <header className="px-8 pt-10 pb-6 border-b border-white/5 flex justify-between items-center shrink-0">
            <h2 className="text-xl font-black uppercase tracking-widest text-purple-500">Archive Index</h2>
            <button onClick={() => setShowChapters(false)} className="bg-neutral-900 p-2.5 rounded-full text-neutral-500 active:scale-90"><X size={20}/></button>
          </header>
          <div className="flex-1 overflow-y-auto p-4 no-scrollbar max-w-2xl mx-auto w-full">
            {chapters.map((ch, i) => (
              <button key={i} onClick={() => { if(audioRef.current) { audioRef.current.currentTime = ch.start; setCurrentTime(ch.start); setShowChapters(false); }}} className={`w-full flex items-center justify-between p-6 rounded-[32px] mb-3 transition-all ${currentChapterIndex === i ? 'bg-purple-600/10 border border-purple-600/30' : 'hover:bg-neutral-900 border border-transparent'}`}>
                <div className="flex flex-col items-start gap-1">
                  <span className={`text-sm font-black uppercase tracking-tight text-left ${currentChapterIndex === i ? 'text-purple-500' : 'text-neutral-300'}`}>{ch.title}</span>
                  <span className="text-[9px] font-black text-neutral-600 uppercase tracking-widest">{formatTime(ch.end - ch.start)} Entry</span>
                </div>
                {currentChapterIndex === i ? <Activity size={16} className="text-purple-500 animate-pulse" /> : <span className="text-[10px] font-mono text-neutral-800">{formatTime(ch.start)}</span>}
              </button>
            ))}
          </div>
        </div>
      )}

      {showInfo && (
        <div className="fixed inset-0 z-[100] animate-fade-in flex items-center justify-center p-6 bg-black/95 backdrop-blur-xl">
          <div className="bg-neutral-900 w-full max-w-xl rounded-[56px] border border-white/10 overflow-hidden flex flex-col max-h-[85vh]">
             <div className="p-10 space-y-8 overflow-y-auto no-scrollbar">
                <div className="flex justify-between items-start">
                   <div className="space-y-2">
                     <h3 className="text-3xl font-black uppercase tracking-tighter text-white leading-none">{item.media.metadata.title}</h3>
                     <p className="text-purple-500 text-[11px] font-black uppercase tracking-[0.4em]">{item.media.metadata.authorName}</p>
                   </div>
                   <button onClick={() => setShowInfo(false)} className="p-3 bg-black/40 rounded-full text-neutral-500 active:scale-90"><X size={24}/></button>
                </div>
                <div className="space-y-4">
                   <h4 className="text-[10px] font-black uppercase tracking-[0.5em] text-neutral-700">Archive Notes</h4>
                   <p className="text-[13px] text-neutral-400 font-medium leading-relaxed uppercase tracking-wide">{item.media.metadata.description || 'No archive description available.'}</p>
                </div>
                <div className="pt-8 border-t border-white/5 grid grid-cols-2 gap-10">
                   <div className="space-y-2">
                      <span className="text-[9px] font-black text-neutral-700 uppercase tracking-widest">Total Duration</span>
                      <p className="text-sm font-black text-white font-mono">{formatTime(duration)}</p>
                   </div>
                   <div className="space-y-2">
                      <span className="text-[9px] font-black text-neutral-700 uppercase tracking-widest">Archive Depth</span>
                      <p className="text-sm font-black text-white font-mono">{chapters.length} Records</p>
                   </div>
                </div>
             </div>
             <button onClick={() => setShowInfo(false)} className="w-full py-8 bg-white/5 text-[11px] font-black uppercase tracking-[0.6em] text-neutral-500 hover:bg-white/10 transition-colors border-t border-white/5">Close Portal</button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Player;
