// components/Player.vue

<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed, watch, nextTick } from 'vue';
import { AuthState, ABSLibraryItem, ABSChapter } from '../types';
import { ABSService } from '../services/absService';
import Hls from 'hls.js';
import { 
  ChevronDown, Play, Pause, Info, X, Activity, Plus, Minus, 
  AlertCircle, RotateCcw, RotateCw, List, Timer
} from 'lucide-vue-next';

const props = defineProps<{
  auth: AuthState,
  item: ABSLibraryItem
}>();

const emit = defineEmits<{
  (e: 'back'): void
}>();

const audioRef = ref<HTMLAudioElement | null>(null);
const hlsInstance = ref<Hls | null>(null);
const isPlaying = ref(false);
const currentTime = ref(0);
const duration = ref(props.item.media.duration || 0);
const chapters = ref<ABSChapter[]>([]);
const playbackSpeed = ref(1.0);
const sleepSeconds = ref(0);
const isLoading = ref(true);
const seekLoading = ref(false);
const error = ref<string | null>(null);
const bufferPercent = ref(0);

const showChapters = ref(false);
const showInfo = ref(false);

const absService = new ABSService(props.auth.serverUrl, props.auth.user?.token || '');
const coverUrl = computed(() => absService.getCoverUrl(props.item.id));

const currentChapterIndex = computed(() => {
  if (!chapters.value.length) return -1;
  return chapters.value.findIndex((ch, i) => 
    currentTime.value >= ch.start && (i === chapters.value.length - 1 || currentTime.value < (chapters.value[i+1]?.start || ch.end))
  );
});

const currentChapter = computed(() => currentChapterIndex.value !== -1 ? chapters.value[currentChapterIndex.value] : null);
const timeRemaining = computed(() => Math.max(0, duration.value - currentTime.value));
const progressPercent = computed(() => duration.value ? (currentTime.value / duration.value) * 100 : 0);

const secondsToTimestamp = (s: number) => {
  if (isNaN(s) || s < 0) return "00:00";
  const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), sec = Math.floor(s % 60);
  return `${h > 0 ? h + ':' : ''}${m.toString().padStart(h > 0 ? 2 : 1, '0')}:${sec.toString().padStart(2, '0')}`;
};

const togglePlay = async () => {
  if (!audioRef.value || isLoading.value) return;
  audioRef.value.paused ? await audioRef.value.play() : audioRef.value.pause();
};

const seek = (time: number) => {
  if (!audioRef.value || isLoading.value) return;
  const target = Math.max(0, Math.min(time, duration.value));
  audioRef.value.currentTime = target;
  currentTime.value = target;
};

const saveProgress = () => {
  if (audioRef.value && audioRef.value.currentTime > 0) {
    absService.saveProgress(props.item.id, audioRef.value.currentTime, duration.value);
  }
};

onMounted(async () => {
  try {
    const details = await absService.getItemDetails(props.item.id);
    chapters.value = details.media.chapters || [];
    duration.value = details.media.duration || props.item.media.duration || 0;
    
    const progress = details.userProgress || await absService.getProgress(props.item.id);
    const startAt = progress?.currentTime || 0;

    await nextTick();
    const audio = audioRef.value;
    if (audio) {
      audio.crossOrigin = 'anonymous';
      const hlsUrl = absService.getHlsStreamUrl(props.item.id);

      if (Hls.isSupported()) {
        const hls = new Hls({ 
          startPosition: startAt,
          xhrSetup: (xhr) => {
            xhr.withCredentials = true;
            xhr.setRequestHeader('Authorization', `Bearer ${props.auth.user?.token}`);
          }
        });
        hlsInstance.value = hls;
        hls.attachMedia(audio);
        hls.on(Hls.Events.MEDIA_ATTACHED, () => hls.loadSource(hlsUrl));
        hls.on(Hls.Events.MANIFEST_PARSED, () => {
          isLoading.value = false;
        });
        hls.on(Hls.Events.BUFFER_APPENDED, () => {
          if (audio.buffered.length) bufferPercent.value = (audio.buffered.end(audio.buffered.length - 1) / duration.value) * 100;
        });
      } else if (audio.canPlayType('application/vnd.apple.mpegurl')) {
        audio.src = hlsUrl;
        audio.addEventListener('canplay', () => {
          audio.currentTime = startAt;
          isLoading.value = false;
        }, { once: true });
      }
    }
  } catch (e: any) {
    error.value = e.message || "Archive Link Severed";
  }
  setInterval(saveProgress, 10000);
});

onUnmounted(() => {
  saveProgress();
  if (hlsInstance.value) hlsInstance.value.destroy();
});

watch(playbackSpeed, (val) => { if (audioRef.value) audioRef.value.playbackRate = val; });
</script>

<template>
  <div class="h-[100dvh] w-full bg-black text-white flex flex-col relative overflow-hidden font-sans select-none safe-top safe-bottom">
    <audio ref="audioRef" @timeupdate="(e: any) => currentTime = e.target.currentTime" @play="isPlaying = true" @pause="isPlaying = false" crossorigin="anonymous" />

    <!-- Header -->
    <header class="px-8 pt-8 pb-4 flex justify-between items-center z-20 shrink-0">
      <button @click="emit('back')" class="bg-neutral-900/40 p-3 rounded-2xl border border-white/5 active:scale-90 transition-all">
        <X :size="20" class="text-neutral-500" />
      </button>
      <button @click="showChapters = true" class="flex items-center gap-3 bg-neutral-900/60 pl-5 pr-4 py-2.5 rounded-full border border-white/5 active:scale-95 transition-all max-w-[60%]">
        <span class="text-[10px] font-black uppercase tracking-widest text-purple-500 truncate">{{ currentChapter?.title || 'Index' }}</span>
        <List :size="16" class="text-purple-500 shrink-0" />
      </button>
      <button @click="showInfo = true" class="bg-neutral-900/40 p-3 rounded-2xl border border-white/5 active:scale-90 transition-all">
        <Info :size="20" class="text-neutral-500" />
      </button>
    </header>

    <!-- Content -->
    <div class="flex-1 flex flex-col items-center justify-center px-8 relative">
      <div class="relative w-full max-w-[320px] aspect-square">
        <div class="absolute -inset-10 bg-purple-600/10 blur-[100px] rounded-full" />
        <img :src="coverUrl" class="w-full h-full object-cover rounded-[56px] shadow-2xl border border-white/10 relative z-10" />
      </div>
      <div class="mt-10 text-center space-y-2">
        <h1 class="text-2xl font-black uppercase tracking-tighter">{{ item.media.metadata.title }}</h1>
        <p class="text-neutral-500 text-[10px] font-black uppercase tracking-[0.4em]">{{ item.media.metadata.authorName }}</p>
      </div>
    </div>

    <!-- Controls -->
    <footer class="px-8 pb-10 space-y-8 max-w-xl mx-auto w-full">
      <div class="space-y-4">
        <div class="flex justify-between text-[10px] font-black font-mono text-neutral-500">
          <span>{{ secondsToTimestamp(currentTime) }}</span>
          <span class="text-purple-500">-{{ secondsToTimestamp(timeRemaining) }}</span>
        </div>
        <div class="h-1.5 w-full bg-neutral-900 rounded-full relative cursor-pointer overflow-hidden" @click="(e: any) => seek((e.offsetX / e.currentTarget.clientWidth) * duration)">
          <div class="absolute inset-y-0 left-0 bg-neutral-800 transition-all" :style="{ width: bufferPercent + '%' }" />
          <div class="absolute inset-y-0 left-0 gradient-aether shadow-aether-glow transition-all" :style="{ width: progressPercent + '%' }" />
        </div>
      </div>

      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3 bg-neutral-900/40 p-2 rounded-2xl border border-white/5">
          <button @click="playbackSpeed = Math.max(0.5, playbackSpeed - 0.1)" class="p-2 text-neutral-500"><Minus :size="14" /></button>
          <span class="text-[10px] font-black font-mono text-purple-500 w-8 text-center">{{ playbackSpeed.toFixed(1) }}x</span>
          <button @click="playbackSpeed = Math.min(2.5, playbackSpeed + 0.1)" class="p-2 text-neutral-500"><Plus :size="14" /></button>
        </div>

        <div class="flex items-center gap-6">
          <button @click="seek(currentTime - 15)" class="text-neutral-500 active:scale-90"><RotateCcw :size="24" /></button>
          <button @click="togglePlay" class="w-20 h-20 rounded-full gradient-aether flex items-center justify-center shadow-aether-glow active:scale-95 transition-all">
            <Pause v-if="isPlaying" :size="32" class="text-white fill-current" />
            <Play v-else :size="32" class="text-white fill-current translate-x-1" />
          </button>
          <button @click="seek(currentTime + 30)" class="text-neutral-500 active:scale-90"><RotateCw :size="24" /></button>
        </div>

        <div class="flex items-center gap-2 bg-neutral-900/40 p-3 rounded-2xl border border-white/5 text-neutral-500">
          <Timer :size="18" />
          <span class="text-[10px] font-black uppercase">Off</span>
        </div>
      </div>
    </footer>
  </div>
</template>

// components/Player.tsx
import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { AuthState, ABSLibraryItem, ABSChapter } from '../types';
import { ABSService } from '../services/absService';
import Hls from 'hls.js';
import { ChevronDown, Play, Pause, SkipBack, SkipForward, Timer, Info, X, Activity, Plus, Minus, AlertCircle, RotateCcw, RotateCw } from 'lucide-react';

interface PlayerProps {
  auth: AuthState;
  item: ABSLibraryItem;
  onBack: () => void;
}

const Player: React.FC<PlayerProps> = ({ auth, item, onBack }) => {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const syncIntervalRef = useRef<number | null>(null);
  const hlsRef = useRef<Hls | null>(null);
  const isMounted = useRef(true);
  const loadTimeoutRef = useRef<number | null>(null);
  const sleepIntervalRef = useRef<number | null>(null);
  
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [chapters, setChapters] = useState<ABSChapter[]>([]);
  const [showChapters, setShowChapters] = useState(false);
  const [showInfo, setShowInfo] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [playbackSpeed, setPlaybackSpeed] = useState(1.0);
  
  // Sleep Timer in Seconds
  const [sleepSeconds, setSleepSeconds] = useState<number>(0);

  const absService = useMemo(() => new ABSService(auth.serverUrl, auth.user?.token || ''), [auth]);
  const duration = item.media.duration || 0;
  const coverUrl = useMemo(() => absService.getCoverUrl(item.id), [item.id, absService]);

  const currentChapterIndex = useMemo(() => {
    if (!chapters.length) return -1;
    return chapters.findIndex((ch, i) => 
      currentTime >= ch.start && (i === chapters.length - 1 || currentTime < (chapters[i+1]?.start || ch.end))
    );
  }, [chapters, currentTime]);

  const currentChapter = useMemo(() => currentChapterIndex !== -1 ? chapters[currentChapterIndex] : null, [chapters, currentChapterIndex]);
  const chapterRemaining = currentChapter ? Math.max(0, currentChapter.end - currentTime) : 0;
  const chapterProgress = currentChapter ? ((currentTime - currentChapter.start) / (currentChapter.end - currentChapter.start)) * 100 : 0;

  // Sleep Timer Countdown Logic
  useEffect(() => {
    if (isPlaying && sleepSeconds > 0) {
      sleepIntervalRef.current = window.setInterval(() => {
        setSleepSeconds(prev => {
          if (prev <= 1) {
            if (audioRef.current) audioRef.current.pause();
            setIsPlaying(false);
            if (sleepIntervalRef.current) clearInterval(sleepIntervalRef.current);
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    } else {
      if (sleepIntervalRef.current) clearInterval(sleepIntervalRef.current);
    }
    return () => { if (sleepIntervalRef.current) clearInterval(sleepIntervalRef.current); };
  }, [isPlaying, sleepSeconds]);

  const togglePlay = useCallback(async () => {
    if (!audioRef.current || isLoading || error) return;
    try {
      if (audioRef.current.paused) {
        await audioRef.current.play();
        setIsPlaying(true);
      } else {
        audioRef.current.pause();
        setIsPlaying(false);
      }
    } catch (err) {
      console.error("Playback toggle failed", err);
    }
  }, [isLoading, error]);

  const skipChapter = useCallback((direction: number) => {
    if (!chapters.length || !audioRef.current) return;
    const targetIdx = Math.max(0, Math.min(chapters.length - 1, currentChapterIndex + direction));
    audioRef.current.currentTime = chapters[targetIdx].start;
    setCurrentTime(chapters[targetIdx].start);
  }, [chapters, currentChapterIndex]);

  const setupMediaSession = useCallback(() => {
    if ('mediaSession' in navigator) {
      navigator.mediaSession.metadata = new MediaMetadata({
        title: item.media.metadata.title,
        artist: item.media.metadata.authorName,
        album: item.media.metadata.seriesName || 'R.S Audio',
        artwork: [{ src: coverUrl, sizes: '512x512', type: 'image/png' }]
      });

      navigator.mediaSession.setActionHandler('play', togglePlay);
      navigator.mediaSession.setActionHandler('pause', togglePlay);
      navigator.mediaSession.setActionHandler('seekbackward', () => { if(audioRef.current) audioRef.current.currentTime -= 15; });
      navigator.mediaSession.setActionHandler('seekforward', () => { if(audioRef.current) audioRef.current.currentTime += 30; });
      navigator.mediaSession.setActionHandler('previoustrack', () => skipChapter(-1));
      navigator.mediaSession.setActionHandler('nexttrack', () => skipChapter(1));
    }
  }, [item, coverUrl, togglePlay, skipChapter]);

  useEffect(() => {
    isMounted.current = true;
    
    const init = async () => {
      setError(null);
      setIsLoading(true);

      loadTimeoutRef.current = window.setTimeout(() => {
        if (isLoading && isMounted.current) {
          setError('Unable to stream from server. Link timed out.');
          setIsLoading(false);
          if (hlsRef.current) hlsRef.current.destroy();
        }
      }, 10000);

      try {
        const [details] = await Promise.all([
          absService.getItemDetails(item.id),
        ]);

        if (!isMounted.current) return;
        if (!details) throw new Error("Unable to fetch item metadata.");

        setChapters(details.media.chapters || []);
        
        let progress = details.userProgress;
        if (!progress) {
          try {
            progress = await absService.getProgress(item.id);
          } catch (e) {
            console.warn("Failed to fetch progress, defaulting to zero.", e);
          }
        }
        
        const startAt = progress?.currentTime || 0;
        const audio = audioRef.current;
        if (audio) {
          audio.crossOrigin = 'anonymous';
          
          // Use the service helper for the requested HLS URL format
          const hlsUrl = absService.getHlsStreamUrl(item.id);
          
          if (Hls.isSupported()) {
            if (hlsRef.current) hlsRef.current.destroy();
            
            const hls = new Hls({ 
              enableWorker: true,
              maxBufferLength: 15,
              maxMaxBufferLength: 30,
              startPosition: startAt,
              autoStartLoad: true,
              lowLatencyMode: true,
              backBufferLength: 60,
              manifestLoadingMaxRetry: 5,
              levelLoadingMaxRetry: 5,
              // VITAL for cross-domain streaming with credentials
              xhrSetup: (xhr) => { xhr.withCredentials = true; }
            });
            
            hlsRef.current = hls;
            hls.attachMedia(audio);
            
            hls.on(Hls.Events.MEDIA_ATTACHED, () => {
              hls.loadSource(hlsUrl);
            });
            
            hls.on(Hls.Events.MANIFEST_PARSED, () => {
              if (isMounted.current) {
                if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
                setIsLoading(false);
              }
            });

            hls.on(Hls.Events.ERROR, (_, data) => {
              if (data.fatal) {
                if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
                switch (data.type) {
                  case Hls.ErrorTypes.NETWORK_ERROR:
                    hls.startLoad();
                    break;
                  case Hls.ErrorTypes.MEDIA_ERROR:
                    hls.recoverMediaError();
                    break;
                  default:
                    if (isMounted.current) {
                      setError("Unable to stream from server. Link failed.");
                      hls.destroy();
                      setIsLoading(false);
                    }
                    break;
                }
              }
            });
          } else if (audio.canPlayType('application/vnd.apple.mpegurl')) {
            audio.src = hlsUrl;
            const onCanPlay = () => {
              if (isMounted.current) {
                if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
                audio.currentTime = startAt;
                setCurrentTime(startAt);
                setIsLoading(false);
              }
              audio.removeEventListener('canplay', onCanPlay);
            };
            audio.addEventListener('canplay', onCanPlay);
            audio.addEventListener('error', () => {
              if (isMounted.current) {
                if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
                setError("Unable to stream from server. Native decoder failed.");
                setIsLoading(false);
              }
            }, { once: true });
          } else {
            throw new Error("HLS playback is not supported in this environment.");
          }

          setupMediaSession();
        }
      } catch (e: any) { 
        if (isMounted.current) {
          if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
          setError(e.message || "Unable to stream from server.");
          setIsLoading(false);
        }
      }
    };

    init();

    return () => { 
      isMounted.current = false;
      if (loadTimeoutRef.current) clearTimeout(loadTimeoutRef.current);
      if (hlsRef.current) hlsRef.current.destroy();
    };
  }, [item.id, absService, auth]);

  const saveProgress = useCallback(() => {
    if (audioRef.current && audioRef.current.currentTime > 0) {
      absService.saveProgress(item.id, audioRef.current.currentTime, duration);
    }
  }, [item.id, duration, absService]);

  useEffect(() => {
    if (isPlaying) syncIntervalRef.current = window.setInterval(saveProgress, 10000);
    return () => { 
      if (syncIntervalRef.current) clearInterval(syncIntervalRef.current); 
      saveProgress(); 
    };
  }, [isPlaying, saveProgress]);

  useEffect(() => {
    if (audioRef.current) audioRef.current.playbackRate = playbackSpeed;
  }, [playbackSpeed]);

  const formatTime = (s: number) => {
    if (isNaN(s)) return "00:00";
    const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), sec = Math.floor(s % 60);
    return `${h > 0 ? h + ':' : ''}${m.toString().padStart(h > 0 ? 2 : 1, '0')}:${sec.toString().padStart(2, '0')}`;
  };

  const handleAdjustSleep = (mins: number) => {
    setSleepSeconds(prev => Math.max(0, prev + (mins * 60)));
  };

  if (isLoading) return (
    <div className="h-[100dvh] flex flex-col items-center justify-center bg-black gap-4 z-50">
      <div className="w-12 h-12 border-4 border-purple-600/20 border-t-purple-600 rounded-full animate-spin" />
      <p className="text-[10px] font-black uppercase tracking-[0.4em] text-neutral-800">Establishing Archive Link...</p>
      <button onClick={onBack} className="mt-8 text-[10px] font-black uppercase tracking-widest text-neutral-500 underline">Abort Sync</button>
    </div>
  );

  if (error) return (
    <div className="h-[100dvh] flex flex-col items-center justify-center bg-black p-10 gap-6 text-center">
      <AlertCircle size={48} className="text-red-500 animate-pulse" />
      <div className="space-y-2">
        <h2 className="text-lg font-black uppercase tracking-tighter text-white">Archive Link Severed</h2>
        <p className="text-[10px] font-black uppercase tracking-widest text-neutral-500">{error}</p>
      </div>
      <button onClick={() => window.location.reload()} className="px-10 py-4 bg-purple-600 rounded-full font-black uppercase text-[10px] tracking-[0.3em] active:scale-95 transition-all shadow-lg">Retry Portal</button>
      <button onClick={onBack} className="text-[10px] font-black uppercase tracking-widest text-neutral-700 hover:text-white transition-colors">Return to Library</button>
    </div>
  );

  return (
    <div className="h-[100dvh] w-full bg-black text-white flex flex-col relative overflow-hidden font-sans select-none">
      <audio 
        ref={audioRef} 
        onTimeUpdate={e => setCurrentTime(e.currentTarget.currentTime)} 
        onPlay={() => setIsPlaying(true)}
        onPause={() => setIsPlaying(false)}
        onEnded={() => setIsPlaying(false)} 
        preload="auto"
        crossOrigin="anonymous"
      />
      
      <header className="px-8 pt-10 pb-4 flex justify-between items-center z-20 shrink-0">
        <button onClick={onBack} className="text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500 bg-neutral-900/40 px-4 py-2 rounded-full border border-white/5 active:scale-95 transition-all">Archive Exit</button>
        <button onClick={() => setShowChapters(true)} className="flex items-center gap-2 bg-neutral-900/60 px-4 py-2 rounded-full border border-white/5 group active:scale-95 transition-all max-w-[50%]">
          <span className="text-[9px] font-black uppercase tracking-[0.2em] text-purple-500 truncate">{currentChapter?.title || 'Index'}</span>
          <ChevronDown size={14} className="text-purple-500 flex-shrink-0" />
        </button>
      </header>

      <div className="flex-1 flex flex-col items-center justify-between px-8 py-4 overflow-hidden">
        <div className="flex-1 w-full flex items-center justify-center mb-6 relative">
          <button onClick={() => setShowInfo(true)} className="aspect-square w-full max-w-[320px] relative group active:scale-95 transition-all shadow-2xl">
            <img src={coverUrl} className="w-full h-full object-cover rounded-[56px] border border-white/10" alt="" />
            <div className="absolute top-6 right-6 p-3 rounded-full bg-black/40 backdrop-blur-xl border border-white/10 opacity-0 group-hover:opacity-100 transition-opacity">
              <Info size={18} className="text-white" />
            </div>
            {sleepSeconds > 0 && (
               <div className="absolute top-6 left-6 flex items-center gap-2 bg-purple-600/90 backdrop-blur-md px-4 py-2 rounded-full border border-white/10 shadow-2xl">
                 <Timer size={14} className="text-white" />
                 <span className="text-[10px] font-black font-mono text-white">{formatTime(sleepSeconds)}</span>
               </div>
            )}
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent rounded-[56px]" />
          </button>
        </div>

        <div className="w-full space-y-6 shrink-0 pb-8 max-w-xl mx-auto">
          <div className="flex flex-col items-center justify-center text-center w-full px-4 space-y-2">
            {item.media.metadata.seriesName && (
              <div className="px-3 py-1 rounded-full bg-neutral-900 border border-white/10 mb-1">
                <span className="text-[9px] font-black uppercase tracking-widest text-neutral-400">{item.media.metadata.seriesName} #{item.media.metadata.sequence}</span>
              </div>
            )}
            <h1 className="text-2xl md:text-3xl font-black uppercase tracking-tighter leading-tight line-clamp-1 w-full">{item.media.metadata.title}</h1>
            <p className="text-neutral-500 text-[10px] font-black uppercase tracking-[0.3em]">{item.media.metadata.authorName}</p>
          </div>

          <div className="flex justify-between items-center px-4">
             <div className="flex flex-col items-start">
               <span className="text-[8px] font-black text-neutral-700 uppercase tracking-widest mb-1">Chapter End</span>
               <span className="text-xs font-mono font-bold text-purple-500">-{formatTime(chapterRemaining)}</span>
             </div>
             <div className="flex flex-col items-end">
               <span className="text-[8px] font-black text-neutral-700 uppercase tracking-widest mb-1">Total Rem.</span>
               <span className="text-xs font-mono font-bold text-neutral-500">{formatTime(duration - currentTime)}</span>
             </div>
          </div>

          <div className="px-2">
            <div className="h-1.5 w-full bg-neutral-900 rounded-full relative overflow-hidden">
              <div className="h-full gradient-aether shadow-aether-glow transition-all duration-300" style={{ width: `${chapterProgress}%` }} />
            </div>
            <div className="flex justify-between mt-3 px-1">
              <span className="text-[9px] font-black text-neutral-700 uppercase tracking-widest truncate max-w-[70%]">{currentChapter?.title || 'Reading...'}</span>
              <span className="text-[9px] font-black text-neutral-700 tabular-nums">{Math.round(chapterProgress)}%</span>
            </div>
          </div>

          <div className="flex items-center justify-center gap-6 md:gap-10 w-full py-4">
            <button onClick={() => { if(audioRef.current) audioRef.current.currentTime -= 15; }} className="p-4 text-neutral-400 hover:text-white transition-all active:scale-75 flex flex-col items-center gap-1">
              <RotateCcw size={28} />
              <span className="text-[8px] font-black">15s</span>
            </button>
            <button onClick={togglePlay} className="w-20 h-20 md:w-24 md:h-24 gradient-aether rounded-full flex items-center justify-center shadow-lg active:scale-95 transition-all">
              {isPlaying ? <Pause size={38} className="text-white fill-current" /> : <Play size={38} className="text-white fill-current translate-x-1" />}
            </button>
            <button onClick={() => { if(audioRef.current) audioRef.current.currentTime += 30; }} className="p-4 text-neutral-400 hover:text-white transition-all active:scale-75 flex flex-col items-center gap-1">
              <RotateCw size={28} />
              <span className="text-[8px] font-black">30s</span>
            </button>
          </div>

          <div className="grid grid-cols-2 gap-4 pb-2">
            <div className="bg-neutral-900/40 rounded-[32px] p-5 flex flex-col items-center justify-center border border-white/5 backdrop-blur-md">
              <span className="text-[8px] font-black text-neutral-700 uppercase tracking-[0.2em] mb-3">Sync Speed</span>
              <div className="flex items-center gap-6">
                <button onClick={() => setPlaybackSpeed(s => Math.max(0.5, s - 0.1))} className="w-10 h-10 flex items-center justify-center bg-black/40 rounded-full text-neutral-400 hover:text-white active:scale-90 transition-all border border-white/5"><Minus size={16} /></button>
                <span className="text-xs font-black text-purple-500 tracking-widest font-mono">{playbackSpeed.toFixed(1)}x</span>
                <button onClick={() => setPlaybackSpeed(s => Math.min(2.5, s + 0.1))} className="w-10 h-10 flex items-center justify-center bg-black/40 rounded-full text-neutral-400 hover:text-white active:scale-90 transition-all border border-white/5"><Plus size={16} /></button>
              </div>
            </div>

            <div className={`bg-neutral-900/40 rounded-[32px] p-5 flex flex-col items-center justify-center border transition-all backdrop-blur-md ${sleepSeconds > 0 ? 'border-purple-600/40 bg-purple-600/5' : 'border-white/5'}`}>
              <div className="flex items-center gap-2 mb-2">
                <Timer size={10} className={sleepSeconds > 0 ? 'text-purple-500' : 'text-neutral-700'} />
                <span className={`text-[8px] font-black uppercase tracking-[0.2em] ${sleepSeconds > 0 ? 'text-purple-500' : 'text-neutral-700'}`}>Sleep Timer</span>
              </div>
              <div className="flex items-center gap-6">
                <button onClick={() => handleAdjustSleep(-5)} className="w-10 h-10 flex items-center justify-center bg-black/40 rounded-full text-neutral-400 hover:text-white active:scale-90 transition-all border border-white/5"><Minus size={16} /></button>
                <div className="flex flex-col items-center justify-center min-w-[50px]">
                  <span className="text-xs font-black text-white tracking-widest font-mono">{sleepSeconds === 0 ? 'OFF' : formatTime(sleepSeconds)}</span>
                  {sleepSeconds > 0 && <span className="text-[7px] font-black text-purple-500 uppercase tracking-widest mt-0.5">Suspension</span>}
                </div>
                <button onClick={() => handleAdjustSleep(15)} className="w-10 h-10 flex items-center justify-center bg-black/40 rounded-full text-neutral-400 hover:text-white active:scale-90 transition-all border border-white/5"><Plus size={16} /></button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {showChapters && (
        <div className="fixed inset-0 z-[100] animate-fade-in flex flex-col bg-black">
          <header className="px-8 pt-10 pb-6 border-b border-white/5 flex justify-between items-center shrink-0">
            <h2 className="text-xl font-black uppercase tracking-widest text-purple-500">Archive Index</h2>
            <button onClick={() => setShowChapters(false)} className="bg-neutral-900 p-2.5 rounded-full text-neutral-500 active:scale-90"><X size={20}/></button>
          </header>
          <div className="flex-1 overflow-y-auto p-4 no-scrollbar max-w-2xl mx-auto w-full">
            {chapters.map((ch, i) => (
              <button key={i} onClick={() => { if(audioRef.current) { audioRef.current.currentTime = ch.start; setCurrentTime(ch.start); setShowChapters(false); }}} className={`w-full flex items-center justify-between p-6 rounded-[32px] mb-3 transition-all ${currentChapterIndex === i ? 'bg-purple-600/10 border border-purple-600/30' : 'hover:bg-neutral-900 border border-transparent'}`}>
                <div className="flex flex-col items-start gap-1">
                  <span className={`text-sm font-black uppercase tracking-tight text-left ${currentChapterIndex === i ? 'text-purple-500' : 'text-neutral-300'}`}>{ch.title}</span>
                  <span className="text-[9px] font-black text-neutral-600 uppercase tracking-widest">{formatTime(ch.end - ch.start)} Entry</span>
                </div>
                {currentChapterIndex === i ? <Activity size={16} className="text-purple-500 animate-pulse" /> : <span className="text-[10px] font-mono text-neutral-800">{formatTime(ch.start)}</span>}
              </button>
            ))}
          </div>
        </div>
      )}

      {showInfo && (
        <div className="fixed inset-0 z-[100] animate-fade-in flex items-center justify-center p-6 bg-black/95 backdrop-blur-xl">
          <div className="bg-neutral-900 w-full max-w-xl rounded-[56px] border border-white/10 overflow-hidden flex flex-col max-h-[85vh]">
             <div className="p-10 space-y-8 overflow-y-auto no-scrollbar">
                <div className="flex justify-between items-start">
                   <div className="space-y-2">
                     <h3 className="text-3xl font-black uppercase tracking-tighter text-white leading-none">{item.media.metadata.title}</h3>
                     <p className="text-purple-500 text-[11px] font-black uppercase tracking-[0.4em]">{item.media.metadata.authorName}</p>
                   </div>
                   <button onClick={() => setShowInfo(false)} className="p-3 bg-black/40 rounded-full text-neutral-500 active:scale-90"><X size={24}/></button>
                </div>
                <div className="space-y-4">
                   <h4 className="text-[10px] font-black uppercase tracking-[0.5em] text-neutral-700">Archive Notes</h4>
                   <p className="text-[13px] text-neutral-400 font-medium leading-relaxed uppercase tracking-wide">{item.media.metadata.description || 'No archive description available.'}</p>
                </div>
                <div className="pt-8 border-t border-white/5 grid grid-cols-2 gap-10">
                   <div className="space-y-2">
                      <span className="text-[9px] font-black text-neutral-700 uppercase tracking-widest">Total Duration</span>
                      <p className="text-sm font-black text-white font-mono">{formatTime(duration)}</p>
                   </div>
                   <div className="space-y-2">
                      <span className="text-[9px] font-black text-neutral-700 uppercase tracking-widest">Archive Depth</span>
                      <p className="text-sm font-black text-white font-mono">{chapters.length} Records</p>
                   </div>
                </div>
             </div>
             <button onClick={() => setShowInfo(false)} className="w-full py-8 bg-white/5 text-[11px] font-black uppercase tracking-[0.6em] text-neutral-500 hover:bg-white/10 transition-colors border-t border-white/5">Close Portal</button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Player;
